export const schedule = [{
    schedule_id: 28,
    visit_date: "2022-02-11",
    visit_time: "10:00:00",
    estimate_num: 444,
    center_etc: "특이사항 없음",
    agent_etc: "특이사항 없음",
    total_etc: null,
    center_id: 11,
    c_name: "이화유치원",
    c_address: "서울특별시 용산구 이촌로 100-8 동아그린아파트 103동 102호",
    c_zipcode: null,
    c_ph: "123",
    c_faxNum: null,
    complete: "incomplete"
}, {
    schedule_id: 19,
    visit_date: "2022-02-11",
    visit_time: "17:13:12",
    estimate_num: 444,
    center_etc: "특이사항 없음",
    agent_etc: "특이사항 없음",
    total_etc: null,
    center_id: 10,
    c_name: "또도",
    c_address: "서울특별시 용산구 이촌로 100-8 동아그린아파트",
    c_zipcode: null,
    c_ph: "123",
    c_faxNum: null,
    complete: "wating"

}, {
    schedule_id: 21,
    visit_date: "2022-02-11",
    visit_time: "17:13:12",
    estimate_num: 444,
    center_etc: "특이사항 없음",
    agent_etc: "특이사항 없음",
    total_etc: null,
    center_id: 10,
    c_name: "또도",
    c_address: "서울특별시 용산구 이촌로 100-8 동아그린아파트",
    c_zipcode: null,
    c_ph: "123",
    c_faxNum: null,
    complete: "complete"

},{
    schedule_id: 22,
    visit_date: "2022-02-11",
    visit_time: "17:13:12",
    estimate_num: 444,
    center_etc: "특이사항 없음",
    agent_etc: "특이사항 없음",
    total_etc: null,
    center_id: 10,
    c_name: "또도",
    c_address: "서울특별시 용산구 이촌로 100-8 동아그린아파트",
    c_zipcode: null,
    c_ph: "123",
    c_faxNum: null
},{
    schedule_id: 23,
    visit_date: "2022-02-11",
    visit_time: "17:13:12",
    estimate_num: 444,
    center_etc: "특이사항 없음",
    agent_etc: "특이사항 없음",
    total_etc: null,
    center_id: 10,
    c_name: "또도",
    c_address: "서울특별시 용산구 이촌로 100-8 동아그린아파트",
    c_zipcode: null,
    c_ph: "123",
    c_faxNum: null,
    complete: "complete"

},{
    schedule_id: 24,
    visit_date: "2022-02-13",
    visit_time: "17:13:12",
    estimate_num: 444,
    center_etc: "특이사항 없음",
    agent_etc: "특이사항 없음",
    total_etc: null,
    center_id: 10,
    c_name: "또도",
    c_address: "서울특별시 용산구 이촌로 100-8 동아그린아파트",
    c_zipcode: null,
    c_ph: "123",
    c_faxNum: null,
    complete: "incomplete"

},
    {
        schedule_id: 25,
        visit_date: "2022-02-12",
        visit_time: "17:13:12",
        estimate_num: 444,
        center_etc: "특이사항 없음",
        agent_etc: "특이사항 없음",
        total_etc: null,
        center_id: 10,
        c_name: "또도",
        c_address: "서울특별시 용산구 이촌로 100-8 동아그린아파트",
        c_zipcode: null,
        c_ph: "123",
        c_faxNum: null
    }
]